name: flutter_screentime
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0+6

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15
  get: ^4.6.5
  url_launcher: ^6.1.5
  #installed_apps: ^1.3.1
  flutter_inappwebview: ^5.4.3+7
  app_settings: ^4.1.6
  # share_plus: ^7.0.2
  device_apps: 2.2.0
  #lottie: ^2.3.2
  #ninad
  intl: ^0.18.1
  html: ^0.15.0
  permission_handler: ^10.2.0
  usage_stats: ^1.2.0
  app_usage: ^3.0.1
  flutter_switch: ^0.3.2
  change_app_package_name: ^1.1.0
  file: ^6.1.4
  firebase_messaging: ^14.2.5
  flutter_local_notifications: ^13.0.0
  firebase_core: ^2.7.0
  # workmanager: ^0.5.1
  workmanager:
    path: ./packages/workmanager-0.5.1
  qr_code_scanner: ^1.0.1
  background_fetch: ^1.2.1
  dio: ^5.4.0
  logger: ^2.0.2+1
  # dart_format: ^1.4.1
  dart_format: ^0.0.4
  # background_fetch:
  #   git:
  #     url: https://github.com/transistorsoft/flutter_background_fetch
  # app_bundle_block:
  #   # When depending on this package from a real application you should use:
  #   #   app_bundle_block: ^x.y.z
  #   # See https://dart.dev/tools/pub/dependencies#version-constraints
  #   # The example app is bundled with the plugin so we use a path dependency on
  #   # the parent directory to use the current plugin's version.
  #   path: ../app_bundle_block

dev_dependencies:
  flutter_lints: ^2.0.0
  # flutter_lints: ^4.0.0 // nova versao recebida
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/logo-app.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/
    - assets/tutorial/


